"""Deterministic synthetic SEG-Y with irregular geometry. Probe **P5**.

Every measurement banked before this probe used a perfectly regular grid with zero dead
traces. Real surveys are not like that, and each condition here has a failure mode that
is **silent by nature**: a duplicate index tuple overwritten in place loses a trace
without a trace, grid padding presented as sample data is fabrication (**SP12**) and
looks exactly like a very quiet trace, and a sparsity check demoted to a log line is not
a check (**SP11**).

The conditions are written as data, not as ten near-copies of a writer. :func:`make_irregular`
takes an explicit sequence of ``(inline, crossline)`` pairs, so a sparse grid, a ragged
line, a missing line and a duplicate tuple are all the *same* function called with
different pairs. Nothing about the writer decides what a grid should look like, which is
the property that lets a fixture express geometry the converter may not expect.

Determinism is not a nicety. Everything is a pure function of the arguments: no clock,
no unseeded RNG, no environment. Two calls with the same arguments produce byte-identical
files, asserted by a test rather than assumed. See
:func:`tests.fixtures.generators.poststack3d.deterministic_text` for the two upstream
behaviours that make the explicit textual header mandatory rather than decorative.
"""

from __future__ import annotations

from collections import Counter
from collections.abc import Callable, Iterable, Sequence
from dataclasses import dataclass
from pathlib import Path

import numpy as np
from segy.factory import SegyFactory
from segy.schema.base import Endianness
from segy.standards import get_segy_standard

from sdip._pins import (
    SEGY_BINARY_HEADER_BYTES as BINARY_HEADER_BYTES,
)
from sdip._pins import (
    SEGY_TEXTUAL_HEADER_BYTES as TEXTUAL_HEADER_BYTES,
)
from sdip._pins import (
    SEGY_TRACE_HEADER_BYTES as TRACE_HEADER_BYTES,
)
from tests.fixtures.generators.poststack3d import PLANTED_BYTES

DEFAULT_SEED = 20260822
"""Seed pre-registered in ``prereg/P5-irregular-geometry.md``. Committed, so a stranger
reproduces every fixture from the repository alone."""

TEXT_ROWS, TEXT_COLS = 40, 80
"""The textual header is exactly 40 rows of 80 columns, EBCDIC, 3200 bytes."""

DEFAULT_SAMPLES = 16
"""Samples per trace. P5 probes correctness, not scale, so the files stay small."""

INLINE_BYTE, CROSSLINE_BYTE = 189, 193
"""Conventional rev 1 index positions, patched by raw offset for the rev 0 fixture.

Rev 0 declares no ``inline`` or ``crossline`` field — that is precisely the condition
``rev0_minimal`` exists to express. The values still have to go *somewhere*, and the
only defensible somewhere is the byte positions rev 1 later standardised, written
directly rather than through a field the revision does not have.
"""

_TEXT_LINES: tuple[str, ...] = (
    "C 1 SDIP SYNTHETIC FIXTURE - IRREGULAR GEOMETRY (PROBE P5)",
    "C 2 GENERATED BY tests/fixtures/generators/irregular.py",
    "C 3 NO PROPRIETARY OR RESTRICTED DATA - SPECIFICATION 6.6 IS BINDING",
    "C 4 AMPLITUDES ARE ANALYTIC: (ORDINAL+1)*256 + T*0.25, EXACT IN IBM32 AND FLOAT32",
    "C 5 A DEAD TRACE IS ALL ZERO - MEASURED, AND INDISTINGUISHABLE FROM PADDING",
    "C 6 BY VALUE ALONE. ONLY THE LIVE MASK CAN TELL THE TWO APART.",
    "C 7 HEADER BYTES 233-240 CARRY PLANTED VALUES FROM A FIXED SEED",
    "C 8 THIS HEADER CONTAINS NO TIMESTAMP, BY DESIGN",
)


def irregular_text(rows: int = TEXT_ROWS, cols: int = TEXT_COLS) -> str:
    """Textual header content: fixed, correctly shaped, and carrying **no timestamp**.

    Args:
        rows: Row count. The rev 1 textual header is 40.
        cols: Column count. The rev 1 textual header is 80.

    Returns:
        Exactly ``rows`` lines of ``cols`` characters, newline separated.
    """
    lines = [line[:cols].ljust(cols) for line in _TEXT_LINES[:rows]]
    lines += ["C".ljust(cols)] * (rows - len(lines))
    return "\n".join(lines)


IRREGULAR_TEXT: str = irregular_text()
"""The committed textual header for every fixture in this module."""


@dataclass(frozen=True, slots=True)
class IrregularSegy:
    """A generated SEG-Y file and the ground truth used to build it."""

    path: Path
    index_pairs: tuple[tuple[int, int], ...]
    dead_ordinals: frozenset[int]
    samples_per_trace: int
    sample_interval_us: int
    revision: int
    endianness: str
    coordinate_scalar: int
    amplitudes: np.ndarray
    planted: np.ndarray
    textual_header: bytes
    binary_header: bytes

    @property
    def trace_count(self) -> int:
        """Number of traces written."""
        return len(self.index_pairs)

    @property
    def byte_size(self) -> int:
        """Size of the written file."""
        return self.path.stat().st_size

    @property
    def inlines(self) -> tuple[int, ...]:
        """Distinct inline numbers present, ascending."""
        return tuple(sorted({inline for inline, _ in self.index_pairs}))

    @property
    def crosslines(self) -> tuple[int, ...]:
        """Distinct crossline numbers present, ascending."""
        return tuple(sorted({crossline for _, crossline in self.index_pairs}))

    @property
    def distinct_cell_count(self) -> int:
        """Distinct ``(inline, crossline)`` tuples. Below ``trace_count`` iff duplicated."""
        return len(set(self.index_pairs))

    @property
    def duplicate_pairs(self) -> tuple[tuple[int, int], ...]:
        """Index tuples claimed by more than one trace. Each one is potential data loss."""
        counts = Counter(self.index_pairs)
        return tuple(sorted(pair for pair, count in counts.items() if count > 1))

    @property
    def padding_cell_count(self) -> int:
        """Cells in the ``inlines x crosslines`` grid that no source trace populates.

        These are the cells that regularisation has to invent. They are **not data**
        (**SP12**), and Plane 4 must exclude rather than compare them.
        """
        return len(self.inlines) * len(self.crosslines) - self.distinct_cell_count

    def ordinals_for(self, inline: int, crossline: int) -> tuple[int, ...]:
        """Source ordinals carrying one index tuple. Length > 1 means a duplicate."""
        return tuple(
            ordinal for ordinal, pair in enumerate(self.index_pairs) if pair == (inline, crossline)
        )


def _analytic_amplitudes(n_traces: int, n_samples: int, dead_ordinals: Iterable[int]) -> np.ndarray:
    """Amplitudes from a closed-form expression, exact in both ibm32 and float32.

    **Not random, and not a saved buffer.** Specification Appendix A.4.2 records the
    canonical failure here: a round trip appeared to fail because the *expectation* was a
    saved sample-template buffer holding an IBM-encoded view, so the comparison was
    invalid — the library was right and the test was wrong. Ground truth is therefore
    computed, not stored.

    Every value is a multiple of ``0.25`` below ``2**16``, so the IBM32 mantissa holds it
    with no rounding and so does float32. The declared ibm32 to float32 decode is
    therefore exactly invertible on this data and Plane 4 can compare with equality.

    A dead trace is **all zero** — a measured zero, byte-identical to the zeros that
    regularisation padding would put in the same array. Distinguishing the two is not
    possible by value and must come from the live mask. That is the point of the fixture.
    """
    ordinal = np.arange(n_traces, dtype=np.float32).reshape(-1, 1)
    sample = np.arange(n_samples, dtype=np.float32).reshape(1, -1)
    values = (ordinal + 1.0) * 256.0 + sample * 0.25
    dead = sorted(set(dead_ordinals))
    if dead:
        values[dead, :] = 0.0
    return values.astype(np.float32)


def _int32_bytes(value: int, endianness: str) -> bytes:
    """Encode a signed 32-bit index value in the file's byte order."""
    return int(value).to_bytes(4, "big" if endianness == "big" else "little", signed=True)


def make_irregular(
    path: str | Path,
    *,
    index_pairs: Sequence[tuple[int, int]],
    n_samples: int = DEFAULT_SAMPLES,
    sample_interval_us: int = 4000,
    revision: int = 1,
    coordinate_scalar: int = 1,
    dead_ordinals: Iterable[int] = (),
    endianness: str = "big",
    seed: int = DEFAULT_SEED,
    text: str = IRREGULAR_TEXT,
) -> IrregularSegy:
    """Write a deterministic synthetic SEG-Y with an explicitly given trace geometry.

    Traces are written in the order given. Nothing sorts, deduplicates or regularises
    them, because a generator that tidies its input cannot express the conditions this
    probe exists to test.

    Args:
        path: Where to write the file.
        index_pairs: ``(inline, crossline)`` per trace, in file order. Repeating a pair
            produces a duplicate index tuple; omitting cells produces a sparse grid.
        n_samples: Samples per trace.
        sample_interval_us: Sample interval in microseconds.
        revision: SEG-Y revision to write. Rev 0 declares no index fields, so they are
            patched in by raw byte offset.
        coordinate_scalar: Value for trace header byte 71. ``0``, positive and negative
            values are all ordinary in production data and all mean different things.
        dead_ordinals: Source ordinals whose samples are all zero — measured dead traces.
        endianness: ``"big"`` or ``"little"``. The little variant exercises a byte order
            SDIP's ingest has no way to declare.
        seed: Seed for the planted header bytes. Fixed and committed.
        text: Textual header content, defaulting to :data:`IRREGULAR_TEXT`. Passing
            ``None`` is **not** supported: the upstream default embeds a timestamp.

    Returns:
        The file plus the ground truth it was built from.

    Raises:
        ValueError: If a file header does not encode to its mandated length.
    """
    target = Path(path)
    spec = get_segy_standard(revision).model_copy(deep=True)
    if endianness == "little":
        # Assignment propagates to the binary-header and trace sub-specs through the
        # model validator, so the whole file is written in one byte order.
        spec.endianness = Endianness.LITTLE
    factory = SegyFactory(spec, sample_interval=sample_interval_us, samples_per_trace=n_samples)

    pairs = tuple((int(inline), int(crossline)) for inline, crossline in index_pairs)
    n_traces = len(pairs)
    dead = frozenset(int(o) for o in dead_ordinals)
    amplitudes = _analytic_amplitudes(n_traces, n_samples, dead)

    rng = np.random.default_rng(seed)
    planted = rng.integers(0, 256, size=(n_traces, len(PLANTED_BYTES)), dtype=np.uint8)

    headers = factory.create_trace_header_template(size=n_traces)
    samples = factory.create_trace_sample_template(size=n_traces)
    declared = set(headers.dtype.names or ())

    for ordinal, (inline, crossline) in enumerate(pairs):
        if "inline" in declared:
            headers["inline"][ordinal] = inline
            headers["crossline"][ordinal] = crossline
        if "cdp_x" in declared:
            headers["cdp_x"][ordinal] = 1_000_000 + crossline * 25
            headers["cdp_y"][ordinal] = 2_000_000 + inline * 25
        headers["coordinate_scalar"][ordinal] = coordinate_scalar
        headers["trace_seq_num_line"][ordinal] = ordinal + 1
        samples[ordinal] = amplitudes[ordinal]

    textual_header = factory.create_textual_header(text)
    if len(textual_header) != TEXTUAL_HEADER_BYTES:
        msg = (
            f"textual header encoded to {len(textual_header)} bytes, must be "
            f"{TEXTUAL_HEADER_BYTES}. Upstream does not pad or validate: a short text "
            f"silently produces a malformed SEG-Y with every later offset wrong."
        )
        raise ValueError(msg)
    binary_header = factory.create_binary_header()
    if len(binary_header) != BINARY_HEADER_BYTES:  # pragma: no cover - upstream invariant
        msg = f"binary header encoded to {len(binary_header)} bytes, must be {BINARY_HEADER_BYTES}"
        raise ValueError(msg)

    body = bytearray(factory.create_traces(headers, samples))
    stride = TRACE_HEADER_BYTES + n_samples * 4
    for ordinal, (inline, crossline) in enumerate(pairs):
        base = ordinal * stride
        # Planted values go in by raw offset: bytes 233-240 are the ones rev 1 leaves
        # uncovered, so the fixture must not depend on a spec that covers them.
        for k, byte_position in enumerate(PLANTED_BYTES):
            body[base + byte_position - 1] = int(planted[ordinal, k])
        if "inline" not in declared:
            body[base + INLINE_BYTE - 1 : base + INLINE_BYTE + 3] = _int32_bytes(inline, endianness)
            body[base + CROSSLINE_BYTE - 1 : base + CROSSLINE_BYTE + 3] = _int32_bytes(
                crossline, endianness
            )

    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_bytes(textual_header + binary_header + bytes(body))

    return IrregularSegy(
        path=target,
        index_pairs=pairs,
        dead_ordinals=dead,
        samples_per_trace=n_samples,
        sample_interval_us=sample_interval_us,
        revision=revision,
        endianness=endianness,
        coordinate_scalar=coordinate_scalar,
        amplitudes=amplitudes,
        planted=planted,
        textual_header=textual_header,
        binary_header=binary_header,
    )


def _regular_pairs(inlines: Iterable[int], crosslines: Iterable[int]) -> list[tuple[int, int]]:
    """Full cross product, inline-major. The regular baseline the conditions deform."""
    return [(inline, crossline) for inline in inlines for crossline in crosslines]


# ---------------------------------------------------------------------------
# The ten pre-registered conditions
# ---------------------------------------------------------------------------


def make_dead_traces(path: str | Path) -> IrregularSegy:
    """Live and dead traces interleaved on a complete grid. 8 x 10 = 80 traces.

    The grid is deliberately **complete**, so there is no padding anywhere and every
    zero-valued cell in the store is a zero somebody measured. A live mask that marks
    those cells dead is claiming the survey did not record them.
    """
    pairs = _regular_pairs(range(100, 108), range(200, 210))
    return make_irregular(path, index_pairs=pairs, dead_ordinals=range(0, len(pairs), 3))


def make_duplicate_index(path: str | Path) -> IrregularSegy:
    """Two traces carrying identical inline and crossline. 30 traces, 29 distinct cells.

    Ordinal 11 is rewritten to claim ordinal 10's cell. Their amplitudes and planted
    header bytes differ, so whichever one reaches the store, the other's absence is
    demonstrable rather than arguable.
    """
    pairs = _regular_pairs(range(100, 105), range(200, 206))
    pairs[11] = pairs[10]
    return make_irregular(path, index_pairs=pairs)


def make_sparse_grid(path: str | Path) -> IrregularSegy:
    """Three small clusters in a wide index range: a grid that is mostly unpopulated.

    Two of the traces are measured zeros. With padding present in the same array, this
    is the fixture where "can the mask tell a dead trace from padding" is a question
    with a checkable answer rather than a slogan.
    """
    clusters = (
        _regular_pairs(range(100, 103), range(200, 203))
        + _regular_pairs(range(140, 143), range(260, 263))
        + _regular_pairs(range(180, 183), range(320, 323))
    )
    return make_irregular(path, index_pairs=clusters, dead_ordinals=(4, 22))


def make_ragged_lines(path: str | Path) -> IrregularSegy:
    """Inlines of differing crossline extent. Lines of 10, 4, 7, 2 and 9 traces.

    Every line starts at crossline 200 and stops where the acquisition stopped, which is
    what a survey edge actually looks like.
    """
    extents = (10, 4, 7, 2, 9)
    pairs = [
        (100 + line, 200 + offset)
        for line, extent in enumerate(extents)
        for offset in range(extent)
    ]
    return make_irregular(path, index_pairs=pairs)


def make_missing_lines(path: str | Path) -> IrregularSegy:
    """Whole inlines absent from the middle of the range. 104, 105 and 106 never appear.

    The gap is interior, not at an edge: an inline range of 100-109 with a hole in it is
    the case where a store that silently renumbers its axis looks completely healthy.
    """
    inlines = [i for i in range(100, 110) if i not in {104, 105, 106}]
    return make_irregular(path, index_pairs=_regular_pairs(inlines, range(200, 206)))


def make_coord_scalar_zero(path: str | Path) -> IrregularSegy:
    """Coordinate scalar ``0``. Undefined by the standard and common in the wild."""
    return make_irregular(
        path, index_pairs=_regular_pairs(range(100, 104), range(200, 205)), coordinate_scalar=0
    )


def make_coord_scalar_pos(path: str | Path) -> IrregularSegy:
    """Coordinate scalar ``+100``: coordinates are to be **multiplied** by 100."""
    return make_irregular(
        path, index_pairs=_regular_pairs(range(100, 104), range(200, 205)), coordinate_scalar=100
    )


def make_coord_scalar_neg(path: str | Path) -> IrregularSegy:
    """Coordinate scalar ``-100``: coordinates are to be **divided** by 100."""
    return make_irregular(
        path, index_pairs=_regular_pairs(range(100, 104), range(200, 205)), coordinate_scalar=-100
    )


def make_byte_swapped(path: str | Path, *, endianness: str = "little") -> IrregularSegy:
    """One logical file in a chosen byte order. The little-endian variant is the probe.

    SEG-Y is a big-endian format by convention and little-endian files exist anyway.
    Building both variants from identical arguments means any difference in outcome is
    attributable to byte order and to nothing else.
    """
    return make_irregular(
        path,
        index_pairs=_regular_pairs(range(100, 104), range(200, 205)),
        endianness=endianness,
    )


def make_rev0_minimal(path: str | Path) -> IrregularSegy:
    """Rev 0 with minimum viable header content.

    Rev 0 declares 71 trace-header fields and none of them is ``inline``, ``crossline``,
    ``cdp_x`` or ``cdp_y``: those positions were standardised later. The index values are
    written at the byte offsets rev 1 would use, which is the most a rev 0 file can do
    and exactly what real rev 0 data does.
    """
    return make_irregular(
        path, index_pairs=_regular_pairs(range(100, 104), range(200, 205)), revision=0
    )


FIXTURE_BUILDERS: dict[str, Callable[[Path], IrregularSegy]] = {
    "dead_traces": make_dead_traces,
    "duplicate_index": make_duplicate_index,
    "sparse_grid": make_sparse_grid,
    "ragged_lines": make_ragged_lines,
    "missing_lines": make_missing_lines,
    "coord_scalar_zero": make_coord_scalar_zero,
    "coord_scalar_pos": make_coord_scalar_pos,
    "coord_scalar_neg": make_coord_scalar_neg,
    "byte_swapped": make_byte_swapped,
    "rev0_minimal": make_rev0_minimal,
}
"""The ten pre-registered conditions, by name. The table in the pre-registration is the
contract; this dictionary is that table, executable."""

FIXTURE_NAMES: tuple[str, ...] = tuple(FIXTURE_BUILDERS)
"""Fixture names in pre-registration order."""


def build_fixture(name: str, path: str | Path) -> IrregularSegy:
    """Build one pre-registered fixture by name.

    Args:
        name: A key of :data:`FIXTURE_BUILDERS`.
        path: Where to write the file.

    Returns:
        The generated fixture.

    Raises:
        KeyError: If ``name`` is not one of the ten pre-registered conditions.
    """
    if name not in FIXTURE_BUILDERS:
        msg = f"unknown P5 fixture {name!r}; pre-registered: {', '.join(FIXTURE_NAMES)}"
        raise KeyError(msg)
    return FIXTURE_BUILDERS[name](Path(path))
