"""Synthetic 3D poststack SEG-Y with known values planted in the header tail.

Mirrors the test article banked in specification Appendix A.1: a small regular 3D
poststack volume with **distinct known values planted in header bytes 233-240 of every
trace** — the bytes the rev 1 standard does not cover.

Those planted bytes are the entire point. They are what a sparse spec silently drops, so
a fixture without them cannot distinguish a converter that preserves the full 240-byte
header from one that only preserves what a template happened to name. Plane 3 is
untestable without them.

Everything is a pure function of the arguments. No clock, no RNG without a seed, no
environment. Two calls with the same arguments produce byte-identical files, asserted by
a test rather than assumed.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

import numpy as np
from segy.factory import SegyFactory
from segy.standards import get_segy_standard

from sdip._pins import (
    SEGY_BINARY_HEADER_BYTES as BINARY_HEADER_BYTES,
)
from sdip._pins import (
    SEGY_TEXTUAL_HEADER_BYTES as TEXTUAL_HEADER_BYTES,
)
from sdip._pins import (
    SEGY_TRACE_HEADER_BYTES as TRACE_HEADER_BYTES,
)

PLANTED_BYTES: tuple[int, ...] = tuple(range(233, 241))
"""Header bytes carrying planted values. Exactly the bytes rev 1 leaves uncovered."""

DEFAULT_SEED = 20260822
"""Fixed seed. Committed, so a stranger reproduces the fixture from the repository."""

TEXT_ROWS, TEXT_COLS = 40, 80
"""The rev 1 textual header is exactly 40 rows of 80 columns, EBCDIC, 3200 bytes."""

_TEXT_LINES: tuple[str, ...] = (
    "C 1 SDIP SYNTHETIC FIXTURE - 3D POSTSTACK",
    "C 2 GENERATED BY tests/fixtures/generators/poststack3d.py",
    "C 3 NO PROPRIETARY OR RESTRICTED DATA - SPECIFICATION 6.6 IS BINDING",
    "C 4 AMPLITUDES ARE ANALYTIC: IL*1024 + XL*4 + T*0.25, EXACT IN FLOAT32",
    "C 5 HEADER BYTES 233-240 CARRY PLANTED VALUES FROM A FIXED SEED",
    "C 6 THOSE BYTES ARE UNCOVERED BY THE REV 1 STANDARD - THAT IS THE POINT",
    "C 7 THIS HEADER CONTAINS NO TIMESTAMP, BY DESIGN",
)


def deterministic_text(rows: int = TEXT_ROWS, cols: int = TEXT_COLS) -> str:
    """Textual header content: fixed, correctly shaped, and carrying **no timestamp**.

    Two upstream behaviours make this function necessary rather than decorative, both
    measured against the pinned ``segy`` 0.6.0:

    **1. The default embeds a timestamp.** ``create_textual_header()`` with no argument
    calls ``get_default_text()``, which writes
    ``datetime.now(tz=UTC).isoformat(timespec="seconds")`` into line 6. Two fixture
    builds therefore differ whenever they straddle a second boundary — **flaky, not
    reliably broken**, which is the worse failure mode: it passes locally and fails in
    CI, 3200 bytes into a binary file where nobody looks. That would make §6.6's
    "generated deterministically by committed code" false and G6's identical-bytes
    requirement unmeasurable.

    **2. Nothing pads or validates the text.** ``create_textual_header("C 1 HELLO")``
    returns **9 bytes**, not 3200. Every subsequent byte offset in the file is then
    wrong and the SEG-Y is malformed, with no error raised — the docstring says the
    length "should match" the spec and leaves it entirely to the caller.

    So the text is built to exactly ``rows`` lines of ``cols`` characters, and the
    caller asserts the encoded result is 3200 bytes.
    """
    lines = [line[:cols].ljust(cols) for line in _TEXT_LINES[:rows]]
    lines += ["C".ljust(cols)] * (rows - len(lines))
    return "\n".join(lines)


DETERMINISTIC_TEXT: str = deterministic_text()
"""The committed textual header for every fixture in this module."""


@dataclass(frozen=True, slots=True)
class SyntheticSegy:
    """A generated SEG-Y file and the ground truth used to build it."""

    path: Path
    inlines: tuple[int, ...]
    crosslines: tuple[int, ...]
    samples_per_trace: int
    sample_interval_us: int
    revision: int
    amplitudes: np.ndarray
    planted: np.ndarray
    textual_header: bytes
    binary_header: bytes

    @property
    def trace_count(self) -> int:
        """Number of traces written."""
        return len(self.inlines) * len(self.crosslines)

    @property
    def byte_size(self) -> int:
        """Size of the written file."""
        return self.path.stat().st_size

    def amplitude_at(self, inline: int, crossline: int) -> np.ndarray:
        """Ground-truth samples for one trace, by grid position."""
        return self.amplitudes[self.inlines.index(inline), self.crosslines.index(crossline)]


def _analytic_amplitudes(n_inline: int, n_crossline: int, n_samples: int) -> np.ndarray:
    """Amplitudes from a closed-form expression, exactly representable in float32.

    **Not random, and not a saved buffer.** Appendix A.4.2 records the canonical failure
    here: a round trip appeared to fail because the *expectation* was a saved
    sample-template buffer holding an IBM-encoded view, so the comparison was invalid —
    the library was right and the test was wrong.

    Ground truth is therefore computed, not stored, and every value is a small multiple
    of a power of two so that float32 holds it with no rounding. A comparison against
    this can be exact equality, which is what Plane 4 demands.
    """
    il = np.arange(n_inline, dtype=np.float32).reshape(-1, 1, 1)
    xl = np.arange(n_crossline, dtype=np.float32).reshape(1, -1, 1)
    t = np.arange(n_samples, dtype=np.float32).reshape(1, 1, -1)
    return (il * 1024.0 + xl * 4.0 + t * 0.25).astype(np.float32)


def make_poststack3d(
    path: str | Path,
    *,
    n_inline: int = 5,
    n_crossline: int = 6,
    n_samples: int = 32,
    inline_start: int = 100,
    crossline_start: int = 200,
    sample_interval_us: int = 4000,
    revision: int = 1,
    seed: int = DEFAULT_SEED,
    text: str = DETERMINISTIC_TEXT,
) -> SyntheticSegy:
    """Write a deterministic synthetic 3D poststack SEG-Y file.

    Defaults reproduce the Appendix A.1 article: 5 inlines x 6 crosslines x 32 samples
    = 30 traces.

    Args:
        path: Where to write the file.
        n_inline: Inline count.
        n_crossline: Crossline count.
        n_samples: Samples per trace.
        inline_start: First inline number.
        crossline_start: First crossline number.
        sample_interval_us: Sample interval in microseconds.
        revision: SEG-Y revision to write.
        seed: Seed for the planted header bytes. Fixed and committed.
        text: Textual header content. Defaults to :data:`DETERMINISTIC_TEXT`. Passing
            ``None`` explicitly is **not** supported: the upstream default embeds a
            timestamp and would make the fixture non-deterministic.

    Returns:
        The file plus the ground truth it was built from.
    """
    target = Path(path)
    spec = get_segy_standard(revision)
    factory = SegyFactory(spec, sample_interval=sample_interval_us, samples_per_trace=n_samples)

    inlines = tuple(range(inline_start, inline_start + n_inline))
    crosslines = tuple(range(crossline_start, crossline_start + n_crossline))
    n_traces = n_inline * n_crossline

    amplitudes = _analytic_amplitudes(n_inline, n_crossline, n_samples)

    # Planted values are seeded, not arbitrary: a distinct, reproducible byte per
    # trace per planted position, so a swapped or dropped trace is visible in the
    # header tail alone.
    rng = np.random.default_rng(seed)
    planted = rng.integers(0, 256, size=(n_traces, len(PLANTED_BYTES)), dtype=np.uint8)

    headers = factory.create_trace_header_template(size=n_traces)
    samples = factory.create_trace_sample_template(size=n_traces)

    index = 0
    for i, inline in enumerate(inlines):
        for j, crossline in enumerate(crosslines):
            headers["inline"][index] = inline
            headers["crossline"][index] = crossline
            headers["cdp_x"][index] = 1_000_000 + crossline * 25
            headers["cdp_y"][index] = 2_000_000 + inline * 25
            headers["coordinate_scalar"][index] = 1
            headers["trace_seq_num_line"][index] = index + 1
            samples[index] = amplitudes[i, j]
            index += 1

    textual_header = factory.create_textual_header(text)
    if len(textual_header) != TEXTUAL_HEADER_BYTES:
        msg = (
            f"textual header encoded to {len(textual_header)} bytes, must be "
            f"{TEXTUAL_HEADER_BYTES}. Upstream does not pad or validate: a short text "
            f"silently produces a malformed SEG-Y with every later offset wrong."
        )
        raise ValueError(msg)
    binary_header = factory.create_binary_header()
    if len(binary_header) != BINARY_HEADER_BYTES:  # pragma: no cover - upstream invariant
        msg = f"binary header encoded to {len(binary_header)} bytes, must be {BINARY_HEADER_BYTES}"
        raise ValueError(msg)
    body = factory.create_traces(headers, samples)

    # Plant into the raw trace bytes: the fields do not exist in the rev 1 spec, which
    # is precisely why they are the interesting ones. Written by byte offset so the
    # fixture does not depend on a spec that covers them.
    payload = bytearray(body)
    header_size, sample_bytes = TRACE_HEADER_BYTES, n_samples * 4
    stride = header_size + sample_bytes
    for trace in range(n_traces):
        base = trace * stride
        for k, byte_position in enumerate(PLANTED_BYTES):
            payload[base + byte_position - 1] = int(planted[trace, k])

    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_bytes(textual_header + binary_header + bytes(payload))

    return SyntheticSegy(
        path=target,
        inlines=inlines,
        crosslines=crosslines,
        samples_per_trace=n_samples,
        sample_interval_us=sample_interval_us,
        revision=revision,
        amplitudes=amplitudes,
        planted=planted,
        textual_header=textual_header,
        binary_header=binary_header,
    )


def read_planted(path: str | Path, n_traces: int, n_samples: int) -> np.ndarray:
    """Read planted bytes 233-240 back out of a SEG-Y file by raw offset.

    Deliberately does not use any spec: this is the independent reader that makes
    Plane 3 evidence rather than a tautology.
    """
    raw = Path(path).read_bytes()
    body = raw[TEXTUAL_HEADER_BYTES + BINARY_HEADER_BYTES :]
    stride = TRACE_HEADER_BYTES + n_samples * 4
    out = np.zeros((n_traces, len(PLANTED_BYTES)), dtype=np.uint8)
    for trace in range(n_traces):
        base = trace * stride
        for k, byte_position in enumerate(PLANTED_BYTES):
            out[trace, k] = body[base + byte_position - 1]
    return out
