"""Synthetic prestack SEG-Y fixtures for probe **P7**.

Six geometries, one generator, one seed. Each fixture is a small regular gather volume
whose index headers are exactly the ones an MDIO prestack template binds by name.

Why this module exists at all
-----------------------------
Every prestack template MDIO ships binds its dimensions **by trace-header field name**,
and the names it wants — ``cable``, ``channel``, ``gun``, ``sail_line``, ``shot_line``,
``receiver``, ``offset``, ``cdp`` — are not names the SEG-Y rev 1 standard uses. Two of
them exist in rev 1 under a different name at a byte position the industry agrees on
(``offset`` is byte 37, "distance from source point to receiver group"; ``cdp`` is byte
21, "ensemble number"); the rest are acquisition-specific and every vendor places them
where it likes.

So a prestack fixture is not just a trace layout. It is a trace layout **plus a
declaration of where those fields live**, and the declaration has to be carried with the
file — which is what :class:`PrestackGeometry` does and why :func:`prestack_spec` exists.

Determinism
-----------
Everything here is a pure function of the arguments. No clock, no unseeded RNG, no
environment. Two calls with the same arguments produce byte-identical files, asserted by
a test rather than assumed. The two upstream hazards documented in
``tests/fixtures/generators/poststack3d.py`` apply unchanged and are handled the same
way: ``SegyFactory.create_textual_header()`` with no argument embeds ``datetime.now()``,
and it neither pads nor validates, so explicit 40x80 text is passed and the encoded
result is checked to be exactly 3200 bytes.
"""

from __future__ import annotations

import itertools
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

import numpy as np
from segy.factory import SegyFactory
from segy.schema import ScalarType
from segy.schema.header import HeaderField

from sdip._pins import (
    SEGY_BINARY_HEADER_BYTES as BINARY_HEADER_BYTES,
)
from sdip._pins import (
    SEGY_TEXTUAL_HEADER_BYTES as TEXTUAL_HEADER_BYTES,
)
from sdip.spec.generator import build_gap_free_spec

DEFAULT_SEED = 20260822
"""Fixed seed, from the pre-registration. Committed, so a stranger reproduces the file."""

TEXT_ROWS, TEXT_COLS = 40, 80
"""The rev 1 textual header is exactly 40 rows of 80 columns, EBCDIC, 3200 bytes."""

PLANT_FIELD = "device_trace_id"
"""Where the seeded per-trace tag goes: byte 213, ``int16``, declared by rev 1.

No prestack template binds it, so it is inert as far as the conversion is concerned, and
a distinct seeded value per trace makes a dropped or transposed trace visible in the
header alone. This is the prestack counterpart of the planted bytes 233-240 in
``poststack3d.py``; those bytes cannot be used here because several geometries need them
for their index fields.
"""

TRACE_BUDGET = 500
"""Per-fixture trace ceiling from the pre-registration. P7 probes shape, not scale."""

_TEXT_LINES: tuple[str, ...] = (
    "C 1 SDIP SYNTHETIC FIXTURE - PRESTACK GATHERS - PROBE P7",
    "C 2 GENERATED BY tests/fixtures/generators/prestack.py",
    "C 3 NO PROPRIETARY OR RESTRICTED DATA - SPECIFICATION 6.6 IS BINDING",
    "C 4 AMPLITUDES ARE ANALYTIC: ORDINAL*4 + T*0.25, EXACT IN FLOAT32",
    "C 5 INDEX HEADERS ARE DECLARED BY THE GEOMETRY, NOT BY THE REV 1 STANDARD",
    "C 6 BYTE 213 CARRIES A SEEDED PER-TRACE TAG NO TEMPLATE BINDS",
    "C 7 THIS HEADER CONTAINS NO TIMESTAMP, BY DESIGN",
)


def deterministic_text(rows: int = TEXT_ROWS, cols: int = TEXT_COLS) -> str:
    """Textual header content: fixed, correctly shaped, and carrying **no timestamp**.

    See ``poststack3d.deterministic_text`` for the two measured upstream behaviours that
    make this necessary. Both still apply; neither is worked around, both are avoided.
    """
    lines = [line[:cols].ljust(cols) for line in _TEXT_LINES[:rows]]
    lines += ["C".ljust(cols)] * (rows - len(lines))
    return "\n".join(lines)


DETERMINISTIC_TEXT: str = deterministic_text()
"""The committed textual header for every fixture in this module."""


@dataclass(frozen=True, slots=True)
class IndexField:
    """One trace-header field a prestack template binds, and where this fixture puts it.

    ``rationale`` is not decoration. These byte positions are a **choice**, and a choice
    a reader cannot audit is indistinguishable from an accident. It records what the
    rev 1 standard puts at those bytes and why the field displaced it.
    """

    name: str
    byte: int
    fmt: ScalarType
    rationale: str

    def header_field(self) -> HeaderField:
        """The ``segy`` declaration for this field."""
        return HeaderField(name=self.name, byte=self.byte, format=self.fmt)


@dataclass(frozen=True, slots=True)
class Axis:
    """One axis of the fixture's regular trace layout.

    Args:
        name: How derived columns refer to this axis.
        values: The values it takes, in order. The trace order is the cartesian product
            of the axes, outermost first — which is also the order a real acquisition
            writes them.
        write: ``True`` when ``name`` is itself a trace-header field to be written.
            ``False`` for a pure counting axis whose header value is produced by a
            :class:`DerivedColumn` instead — flip-flop shot numbering needs this,
            because ``shot_point`` depends on both the shot counter and the gun.
    """

    name: str
    values: tuple[int, ...]
    write: bool = True


@dataclass(frozen=True, slots=True)
class DerivedColumn:
    """A trace-header column computed from axis **indices**, not axis values.

    ``value = base + sum(index_of(axis) * step)``. Indices rather than values so that a
    coordinate stays inside ``int32`` no matter how the axis is numbered.
    """

    name: str
    axes: tuple[str, ...]
    base: int
    steps: tuple[int, ...] = ()


@dataclass(frozen=True, slots=True)
class PrestackGeometry:
    """One prestack geometry: its template, its index fields, and its trace layout."""

    name: str
    template: str
    index_fields: tuple[IndexField, ...]
    axes: tuple[Axis, ...]
    derived: tuple[DerivedColumn, ...]
    store_dimensions: tuple[str, ...]
    note: str
    n_samples: int = 32
    sample_interval_us: int = 4000
    revision: int = 1

    @property
    def trace_count(self) -> int:
        """Traces the cartesian product of the axes produces."""
        total = 1
        for axis in self.axes:
            total *= len(axis.values)
        return total

    @property
    def declared_names(self) -> tuple[str, ...]:
        """Names this geometry adds to the rev 1 standard spec."""
        return tuple(f.name for f in self.index_fields)


def _shot_flip_flop(base: int) -> tuple[DerivedColumn, ...]:
    """Flip-flop shot numbering: gun 1 takes the even shots, gun 2 the odd ones.

    This is the ``Type B`` geometry MDIO's ``ShotWrappingStrategy`` detects, and it is
    the realistic one — a dual-source vessel interleaves shot points between guns. It is
    chosen deliberately rather than avoided: Type B is the branch that **derives a new
    ``shot_index`` dimension** that appears nowhere in the source file, which is exactly
    the kind of thing this probe exists to find.
    """
    return (
        DerivedColumn("shot_point", ("shot", "gun"), base, (2, 1)),
        DerivedColumn("orig_field_record_num", ("shot", "gun"), base + 4000, (2, 1)),
    )


_CABLE = IndexField(
    "cable",
    233,
    ScalarType.INT16,
    "rev 1 leaves bytes 233-240 unassigned; the gap-free spec covers them with uint8 "
    "fillers, so an int16 here displaces pad_233/pad_234 and nothing standardised",
)
_CHANNEL_235 = IndexField(
    "channel",
    235,
    ScalarType.INT16,
    "unassigned tail, displacing pad_235/pad_236",
)
_GUN_237 = IndexField("gun", 237, ScalarType.INT16, "unassigned tail, displacing pad_237/pad_238")

GEOMETRIES: tuple[PrestackGeometry, ...] = (
    PrestackGeometry(
        name="streamer_shot_3d",
        template="StreamerShotGathers3D",
        index_fields=(_CABLE, _CHANNEL_235, _GUN_237),
        axes=(
            Axis("shot_point", tuple(range(1000, 1004))),
            Axis("cable", (1, 2)),
            Axis("channel", tuple(range(1, 17))),
        ),
        derived=(
            DerivedColumn("gun", (), 1),
            DerivedColumn("source_coord_x", ("shot_point",), 500_000, (2500,)),
            DerivedColumn("source_coord_y", (), 600_000),
            DerivedColumn("group_coord_x", ("shot_point", "channel"), 500_000, (2500, -1200)),
            DerivedColumn("group_coord_y", ("cable",), 600_000, (10_000,)),
        ),
        store_dimensions=("shot_point", "cable", "channel"),
        note="4 shots x 2 cables x 16 channels. Channel numbering is per-cable (Type A).",
    ),
    PrestackGeometry(
        name="streamer_shot_3d_wrapped",
        template="StreamerShotGathers3D",
        index_fields=(_CABLE, _CHANNEL_235, _GUN_237),
        axes=(
            Axis("shot_point", tuple(range(1000, 1004))),
            Axis("cable", (1, 2)),
            Axis("chan", tuple(range(16)), write=False),
        ),
        derived=(
            DerivedColumn("channel", ("cable", "chan"), 1, (16, 1)),
            DerivedColumn("gun", (), 1),
            DerivedColumn("source_coord_x", ("shot_point",), 500_000, (2500,)),
            DerivedColumn("source_coord_y", (), 600_000),
            DerivedColumn("group_coord_x", ("shot_point", "chan"), 500_000, (2500, -1200)),
            DerivedColumn("group_coord_y", ("cable",), 600_000, (10_000,)),
        ),
        store_dimensions=("shot_point", "cable", "channel"),
        note=(
            "The same 4 x 2 x 16 acquisition as streamer_shot_3d, numbered the other "
            "way: channels run 1-16 on cable 1 and 17-32 on cable 2 (Type B). This is "
            "the geometry MDIO's ChannelWrappingStrategy rebases, so it is the one that "
            "says whether a rebased index reaches the store."
        ),
    ),
    PrestackGeometry(
        name="streamer_shot_2d",
        template="StreamerShotGathers2D",
        index_fields=(
            IndexField("channel", 233, ScalarType.INT16, "unassigned tail, displacing pad_233/234"),
        ),
        axes=(
            Axis("shot_point", tuple(range(1000, 1008))),
            Axis("channel", tuple(range(1, 25))),
        ),
        derived=(
            DerivedColumn("source_coord_x", ("shot_point",), 500_000, (2500,)),
            DerivedColumn("source_coord_y", (), 600_000),
            DerivedColumn("group_coord_x", ("shot_point", "channel"), 500_000, (2500, -1200)),
            DerivedColumn("group_coord_y", (), 600_000),
        ),
        store_dimensions=("shot_point", "channel"),
        note="8 shots x 24 channels, single cable.",
    ),
    PrestackGeometry(
        name="streamer_field_3d",
        template="StreamerFieldRecords3D",
        index_fields=(
            _CABLE,
            _CHANNEL_235,
            _GUN_237,
            IndexField(
                "sail_line", 239, ScalarType.INT16, "unassigned tail, displacing pad_239/pad_240"
            ),
        ),
        axes=(
            Axis("sail_line", (10,)),
            Axis("gun", (1, 2)),
            Axis("shot", tuple(range(4)), write=False),
            Axis("cable", (1, 2)),
            Axis("channel", tuple(range(1, 9))),
        ),
        derived=(
            *_shot_flip_flop(1000),
            DerivedColumn("source_coord_x", ("shot", "gun"), 500_000, (2500, 50)),
            DerivedColumn("source_coord_y", (), 600_000),
            DerivedColumn(
                "group_coord_x", ("shot", "gun", "channel"), 500_000, (2500, 50, -1200)
            ),
            DerivedColumn("group_coord_y", ("cable",), 600_000, (10_000,)),
        ),
        store_dimensions=("sail_line", "gun", "shot_index", "cable", "channel"),
        note=(
            "1 sail line x 2 guns x 4 shots x 2 cables x 8 channels, flip-flop shot "
            "numbering. shot_index is calculated by MDIO and is in no source header."
        ),
    ),
    PrestackGeometry(
        name="obn_receiver_3d",
        template="ObnReceiverGathers3D",
        index_fields=(
            IndexField(
                "receiver", 233, ScalarType.INT32, "unassigned tail, displacing pad_233-pad_236"
            ),
            IndexField(
                "shot_line", 237, ScalarType.INT16, "unassigned tail, displacing pad_237/pad_238"
            ),
            IndexField("gun", 239, ScalarType.INT16, "unassigned tail, displacing pad_239/pad_240"),
        ),
        axes=(
            Axis("receiver", tuple(range(1, 9))),
            Axis("shot_line", (20,)),
            Axis("gun", (1, 2)),
            Axis("shot", tuple(range(4)), write=False),
        ),
        derived=(
            *_shot_flip_flop(1000),
            DerivedColumn("group_coord_x", ("receiver",), 400_000, (5000,)),
            DerivedColumn("group_coord_y", (), 700_000),
            DerivedColumn("source_coord_x", ("shot", "gun"), 500_000, (2500, 50)),
            DerivedColumn("source_coord_y", (), 600_000),
        ),
        store_dimensions=("component", "receiver", "shot_line", "gun", "shot_index"),
        note=(
            "8 receivers x 1 shot line x 2 guns x 4 shots. `component` is absent from "
            "the source and synthesised by MDIO; `shot_index` is calculated."
        ),
    ),
    PrestackGeometry(
        name="cdp_offset_3d",
        template="CdpOffsetGathers3DTime",
        index_fields=(
            IndexField(
                "offset",
                37,
                ScalarType.INT32,
                "rev 1 byte 37 IS offset - it is named source_to_receiver_distance. Same "
                "bytes, same width, same meaning; only the name differs",
            ),
        ),
        axes=(
            Axis("inline", tuple(range(100, 104))),
            Axis("crossline", tuple(range(200, 206))),
            Axis("offset", tuple(range(100, 1300, 200))),
        ),
        derived=(
            DerivedColumn("cdp_x", ("crossline",), 1_000_000, (2500,)),
            DerivedColumn("cdp_y", ("inline",), 2_000_000, (2500,)),
        ),
        store_dimensions=("inline", "crossline", "offset"),
        note="4 inlines x 6 crosslines x 6 offsets. The only geometry whose store keeps "
        "an inline and a crossline axis.",
    ),
    PrestackGeometry(
        name="cdp_offset_2d",
        template="CdpOffsetGathers2DTime",
        index_fields=(
            IndexField(
                "cdp",
                21,
                ScalarType.INT32,
                "rev 1 byte 21 IS the CDP - it is named ensemble_num. Same bytes, same "
                "width, same meaning; only the name differs",
            ),
            IndexField(
                "offset",
                37,
                ScalarType.INT32,
                "rev 1 byte 37, named source_to_receiver_distance. Name only",
            ),
        ),
        axes=(
            Axis("cdp", tuple(range(500, 520))),
            Axis("offset", tuple(range(100, 1700, 200))),
        ),
        derived=(
            DerivedColumn("cdp_x", ("cdp",), 1_000_000, (1250,)),
            DerivedColumn("cdp_y", (), 2_000_000),
        ),
        store_dimensions=("cdp", "offset"),
        note="20 CDPs x 8 offsets.",
    ),
)

GEOMETRY_NAMES: tuple[str, ...] = tuple(g.name for g in GEOMETRIES)
"""The geometry table, in order. The probe transcribes this and a test pins the two."""

_BY_NAME: dict[str, PrestackGeometry] = {g.name: g for g in GEOMETRIES}


def geometry(name: str) -> PrestackGeometry:
    """Look one geometry up by name.

    Args:
        name: A member of :data:`GEOMETRY_NAMES`.

    Returns:
        The geometry descriptor.

    Raises:
        KeyError: If the name is not in the table.
    """
    return _BY_NAME[name]


def prestack_spec(geom: PrestackGeometry) -> Any:
    """A gap-free rev 1 spec with the geometry's index fields declared.

    Built by :func:`sdip.spec.generator.build_gap_free_spec` and then customised through
    ``segy``'s own public ``HeaderSpec.customize``, which removes any standard field the
    new declaration overlaps. Byte coverage is therefore preserved exactly — a field
    displaced is a field replaced, never a field dropped — so the result is still
    gap-free.

    **This function does not assert that.** G1 is run by the caller, on purpose: an
    assertion written by the thing it judges is not an assertion (see
    ``sdip/spec/gate.py``).

    Args:
        geom: The geometry whose index fields to declare.

    Returns:
        The customised ``SegySpec``.
    """
    built = build_gap_free_spec(geom.revision)
    spec = built.segy_spec
    spec.trace.header.customize([f.header_field() for f in geom.index_fields])
    return spec


@dataclass(frozen=True, slots=True)
class PrestackSegy:
    """A generated prestack SEG-Y and the ground truth it was built from."""

    path: Path
    geometry: PrestackGeometry
    columns: dict[str, np.ndarray] = field(default_factory=dict)
    amplitudes: np.ndarray = field(default_factory=lambda: np.zeros(0, dtype=np.float32))
    planted: np.ndarray = field(default_factory=lambda: np.zeros(0, dtype=np.int16))
    textual_header: bytes = b""
    binary_header: bytes = b""

    @property
    def name(self) -> str:
        """The geometry name."""
        return self.geometry.name

    @property
    def template(self) -> str:
        """The MDIO template this fixture is built for."""
        return self.geometry.template

    @property
    def trace_count(self) -> int:
        """Number of traces written."""
        return self.geometry.trace_count

    @property
    def samples_per_trace(self) -> int:
        """Samples per trace."""
        return self.geometry.n_samples

    @property
    def byte_size(self) -> int:
        """Size of the written file."""
        return self.path.stat().st_size

    def spec(self) -> Any:
        """The customised gap-free spec this file must be read with."""
        return prestack_spec(self.geometry)


def _axis_indices(geom: PrestackGeometry) -> dict[str, np.ndarray]:
    """Per-trace index along every axis, for the cartesian trace order."""
    ranges = [range(len(axis.values)) for axis in geom.axes]
    grid = np.array(list(itertools.product(*ranges)), dtype=np.int64)
    return {axis.name: grid[:, position] for position, axis in enumerate(geom.axes)}


def _columns(geom: PrestackGeometry) -> dict[str, np.ndarray]:
    """Every trace-header column this geometry writes, as int64 arrays."""
    indices = _axis_indices(geom)
    columns: dict[str, np.ndarray] = {}

    for axis in geom.axes:
        if axis.write:
            columns[axis.name] = np.asarray(axis.values, dtype=np.int64)[indices[axis.name]]

    for column in geom.derived:
        total = np.full(geom.trace_count, column.base, dtype=np.int64)
        for axis_name, step in zip(column.axes, column.steps, strict=True):
            total = total + indices[axis_name] * step
        columns[column.name] = total

    return columns


def _amplitudes(n_traces: int, n_samples: int) -> np.ndarray:
    """Analytic amplitudes, exactly representable in float32.

    ``ordinal * 4 + t * 0.25``: every value is a small multiple of a power of two, so
    float32 holds it with no rounding and the comparison can be exact equality — which
    is what Plane 4 demands and what a saved buffer could not give (Appendix A.4.2).
    Distinct per trace, so a transposition shows up in the samples as well as the header.
    """
    ordinal = np.arange(n_traces, dtype=np.float32).reshape(-1, 1)
    t = np.arange(n_samples, dtype=np.float32).reshape(1, -1)
    return (ordinal * 4.0 + t * 0.25).astype(np.float32)


def make_prestack(
    geom: PrestackGeometry,
    path: str | Path,
    *,
    seed: int = DEFAULT_SEED,
    text: str = DETERMINISTIC_TEXT,
) -> PrestackSegy:
    """Write one deterministic synthetic prestack SEG-Y.

    Args:
        geom: The geometry to build.
        path: Where to write the file.
        seed: Seed for the per-trace tag in :data:`PLANT_FIELD`. Fixed and committed.
        text: Textual header content. Passing ``None`` is **not** supported: the upstream
            default embeds a timestamp and would make the fixture non-deterministic.

    Returns:
        The file plus the ground truth it was built from.

    Raises:
        ValueError: If the encoded textual or binary header is not its mandated length.
    """
    target = Path(path)
    spec = prestack_spec(geom)
    factory = SegyFactory(
        spec,
        sample_interval=geom.sample_interval_us,
        samples_per_trace=geom.n_samples,
    )

    n_traces = geom.trace_count
    columns = _columns(geom)
    amplitudes = _amplitudes(n_traces, geom.n_samples)

    rng = np.random.default_rng(seed)
    planted = rng.integers(1, 32_768, size=n_traces, dtype=np.int16)

    headers = factory.create_trace_header_template(size=n_traces)
    samples = factory.create_trace_sample_template(size=n_traces)

    headers["coordinate_scalar"][:] = 1
    headers["trace_seq_num_line"][:] = np.arange(1, n_traces + 1)
    headers[PLANT_FIELD][:] = planted
    for name, values in columns.items():
        headers[name][:] = values
    samples[:] = amplitudes

    textual_header = factory.create_textual_header(text)
    if len(textual_header) != TEXTUAL_HEADER_BYTES:
        msg = (
            f"textual header encoded to {len(textual_header)} bytes, must be "
            f"{TEXTUAL_HEADER_BYTES}. Upstream does not pad or validate: a short text "
            f"silently produces a malformed SEG-Y with every later offset wrong."
        )
        raise ValueError(msg)
    binary_header = factory.create_binary_header()
    if len(binary_header) != BINARY_HEADER_BYTES:  # pragma: no cover - upstream invariant
        msg = f"binary header encoded to {len(binary_header)} bytes, must be {BINARY_HEADER_BYTES}"
        raise ValueError(msg)

    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_bytes(textual_header + binary_header + factory.create_traces(headers, samples))

    return PrestackSegy(
        path=target,
        geometry=geom,
        columns=columns,
        amplitudes=amplitudes,
        planted=np.asarray(planted),
        textual_header=textual_header,
        binary_header=binary_header,
    )


def build_fixture(name: str, path: str | Path) -> PrestackSegy:
    """Build one geometry by name.

    Args:
        name: A member of :data:`GEOMETRY_NAMES`.
        path: Where to write the file.

    Returns:
        The generated fixture.
    """
    return make_prestack(geometry(name), path)
